In [1]:
import pandas as pd
import numpy as np

## tokenizer and deleting punctuation

In [2]:
from corpy.morphodita import Tokenizer
tokenizer = Tokenizer("czech")
punc='[]{}()"„“!@#$%^=_&*-:/,.\''
def tokeny(clanek):
    cont=[]
    for word in tokenizer.tokenize(clanek):
        cont.append(word)
    nopunc = [char for char in cont if char not in punc]
    return nopunc

## lemmatizer

In [3]:
from corpy.morphodita import Tagger
tagger = Tagger("./czech-morfflex-pdt-161115.tagger")
def lemmatizer(slovo):
    tokens = list(tagger.tag(slovo))
    a=''.join(str(tokens))
    ind1=a.find('a=')
    ind2=a.find("'",ind1+3)
    return a[ind1+3:ind2]

## stopwords

In [4]:
filename = 'stopwords-cs.txt'
stopwords = np.loadtxt(filename, dtype=str,encoding="utf8")
def delete_stopwords(lematizovana_slova):
    return list(set(lematizovana_slova)-set(stopwords))

## load data

In [5]:
df=pd.ExcelFile('C:/Users/vacla/OneDrive/Dokumenty/Audiozprávy/article_archive_cleared.xls')

In [6]:
articles=df.parse('article_archive')
articles.head()

title  \
0  Pokud chceme pandemii udržet pod kontrolou, je...   
1  Hlavní manažer ANO pobíral neoprávněně plný za...   
2  Vzpomeňme si, co udělaly bary loni v létě, mla...   
3  Poslední „Berdychovec“ je za mřížemi. Policie ...   
4  Mezi Českem a sedmi zeměmi bude po první dávce...   

                                                link  \
0  https://www.lidovky.cz/domov/pokud-chceme-pand...   
1  https://www.lidovky.cz/domov/hlavni-manazer-an...   
2  https://www.lidovky.cz/domov/prilisne-rozvolne...   
3  https://www.lidovky.cz/domov/policie-privezla-...   
4  https://www.lidovky.cz/domov/mezi-ceskem-a-sed...   

                                             summary           published  \
0  Příznivý vývoj epidemie koronaviru v Česku lze... 2021-05-28 20:20:00   
1  Hlavní manažer hnutí ANO Jan Richter loni pobí... 2021-05-28 18:53:00   
2  Po zmírnění protiepidemických opatření, ke kte... 2021-05-28 18:03:00   
3  Čeští kriminalisté přivezli z USA Jaromíra Pro... 2021-05-28 18:03:00   
4  Ze Slovenska, Polska, Německa, Rakouska, Maďar... 2021-05-28 18:01:00   

                 tags         category             credit      source  
0  ['Zprávy - Domov']  Zprávy z domova                ČTK  lidovky.cz  
1  ['Zprávy - Domov']  Zprávy z domova              MAFRA  lidovky.cz  
2  ['Zprávy - Domov']  Zprávy z domova  Petr Lundák MAFRA  lidovky.cz  
3  ['Zprávy - Domov']  Zprávy z domova         Policie ČR  lidovky.cz  
4  ['Zprávy - Domov']  Zprávy z domova                ČTK  lidovky.cz

In [134]:
#test
articles=articles[['title','summary']]

### prepare data, merge rows and create dataset

In [135]:
ddd=articles
#ddd['published']=np.datetime_as_string(ddd['published'])
for type in ddd.columns:
    ddd[type]=ddd[type].astype(str)

C:\Users\vacla\AppData\Local\Temp/ipykernel_14216/2376134229.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ddd[type]=ddd[type].astype(str)


In [136]:
ddd

title  \
0     Pokud chceme pandemii udržet pod kontrolou, je...   
1     Hlavní manažer ANO pobíral neoprávněně plný za...   
2     Vzpomeňme si, co udělaly bary loni v létě, mla...   
3     Poslední „Berdychovec“ je za mřížemi. Policie ...   
4     Mezi Českem a sedmi zeměmi bude po první dávce...   
...                                                 ...   
5543  Podle čeho najde Gróňan při návratu z hospody ...   
5544  V čem jsou slabiny a rizika současného světové...   
5545  Ústečtí muzejníci chtějí zachránit přes 100 le...   
5546  Cannes 2021 přineslo sondy do nemocných duší. ...   
5547  Josef Bernard: Stát musí přijít s pobídkami, a...   

                                                summary  
0     Příznivý vývoj epidemie koronaviru v Česku lze...  
1     Hlavní manažer hnutí ANO Jan Richter loni pobí...  
2     Po zmírnění protiepidemických opatření, ke kte...  
3     Čeští kriminalisté přivezli z USA Jaromíra Pro...  
4     Ze Slovenska, Polska, Německa, Rakouska, Maďar...  
...                                                 ...  
5543  Grónský deník Albíny Mrázové: Zdejší krajina s...  
5544  Komentář Ivana Mikloše: Současná situace ve sv...  
5545  Muzeum města Ústí nad Labem se snaží zachránit...  
5546  Zlatou palmu si dnes z&#160;Cannes odnesl lehc...  
5547  Kdy se definitivně rozloučíme s auty se spalov...  

[5548 rows x 2 columns]

In [137]:
for i in range(ddd.shape[0]):
    i1=ddd['published'][i][0:4]
    i2=ddd['published'][i][5:7]
    i3=ddd['published'][i][8:10]
    i4=ddd['published'][i][11:13]
    i5=ddd['published'][i][14:16]
    ddd['published'][i]=str(i1 + ' '+i2+' ' +i3+' ' +i4+' ' +i5 )
    #h=[i1,i2,i3,i4,i5]
    #for j in range(len(h)):
    #    ch=' '.join(h[i])
    #    ddd['published'].append(g)

KeyError: 'published'

In [138]:
data=[]
for i in range(ddd.shape[0]):
    g=' '.join(ddd.loc[i])
    data.append(g)

In [140]:
%%time
databaze=[]
d=[]
for clanek in data:
    d=tokeny(clanek)
    d=delete_stopwords(d) #change 1
    e=[]
    for slovo in d:
        e.append(lemmatizer(slovo))
    #e=delete_stopwords(e)
    databaze.append(e)
        

Wall time: 11.2 s


### to shape of CountVectorizer

In [141]:
dataset=[]
for index in range(len(databaze)):
    store=' '.join(databaze[index])
    dataset.append(store)


In [142]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
train_x_vectors=vectorizer.fit_transform(dataset)

In [143]:
%%time
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances


Wall time: 0 ns


In [102]:
%%time
res=cosine_similarity(train_x_vectors[1],train_x_vectors[0])

Wall time: 2.99 ms


In [108]:
2.99*1000*1000/1000/3600

0.8305555555555556

In [128]:
articles.loc[0:10,['title','summary','published','source']]


title  \
0   Pokud chceme pandemii udržet pod kontrolou, je...   
1   Hlavní manažer ANO pobíral neoprávněně plný za...   
2   Vzpomeňme si, co udělaly bary loni v létě, mla...   
3   Poslední „Berdychovec“ je za mřížemi. Policie ...   
4   Mezi Českem a sedmi zeměmi bude po první dávce...   
5   Děti by se mohly očkovat od konce června, uved...   
6   Volné cestování po první dávce očkování je pln...   
7   Úplné rozvolnění, kvůli soudu vláda od pondělí...   
8   Hamáček na vládě předloží postup, jak odškodni...   
9   Mrhají nadšením vědců, říká o chování státu vi...   
10  Restaurace i bazény se otevřou už od pondělí. ...   

                                              summary         published  \
0   Příznivý vývoj epidemie koronaviru v Česku lze...  2021 05 28 20 20   
1   Hlavní manažer hnutí ANO Jan Richter loni pobí...  2021 05 28 18 53   
2   Po zmírnění protiepidemických opatření, ke kte...  2021 05 28 18 03   
3   Čeští kriminalisté přivezli z USA Jaromíra Pro...  2021 05 28 18 03   
4   Ze Slovenska, Polska, Německa, Rakouska, Maďar...  2021 05 28 18 01   
5   Očkování proti covidu-19 je důležité pro děti ...  2021 05 28 17 30   
6   Ačkoli se Česko odvolává na reciprocitu se sou...  2021 05 28 16 00   
7   Přestřižení posledních proticovidových provazů...  2021 05 28 14 24   
8   Ministr vnitra Jan Hamáček (ČSSD) v pondělí vl...  2021 05 28 14 02   
9   Výzkumný ústav BIOCEV už tři měsíce sekvenuje ...  2021 05 28 14 00   
10  Vláda od pondělka výrazně rozvolní protiepidem...  2021 05 28 13 19   

        source  
0   lidovky.cz  
1   lidovky.cz  
2   lidovky.cz  
3   lidovky.cz  
4   lidovky.cz  
5   lidovky.cz  
6   lidovky.cz  
7   lidovky.cz  
8   lidovky.cz  
9   lidovky.cz  
10  lidovky.cz

In [151]:
articles.loc[446,['title','summary']]


title      Vakcína pro děti nad dvanáct let: Kdy mohou př...
summary    Zítra má Evropská léková agentura (EMA) doporu...
Name: 446, dtype: object

## duplicated articles
* 1 a 441
* 5 a 446

In [145]:
cosine_similarity(train_x_vectors[0],train_x_vectors[4])

array([[0.15308091]])

In [146]:
cosine_similarity(train_x_vectors[1],train_x_vectors[441])

array([[0.54352309]])

In [147]:
cosine_similarity(train_x_vectors[5],train_x_vectors[446])

array([[0.35816181]])

In [148]:
cosine_similarity(train_x_vectors[1],train_x_vectors[10])

array([[0.10006256]])

In [ ]:
0-31 #28 05 - 27 05

In [ ]:
443 a1